
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eugyzwtrbguwafckllfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Z3l6d3RyYmd1d2FmY2tsbGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzI0NjksImV4cCI6MjA2MTkwODQ2OX0.p3SwPdAPUe9Yi4z-7Ou7l4MlijHm5hkjxZrdAVuWEpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'flora-admin-auth'
  }
});
